version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment-woovi
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - postgres_data:/bitnami/postgresql

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: